version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resume_matcher
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - resume-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: ..
      dockerfile: dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8080" 
    depends_on:
      - db
    networks:
      - resume-net

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8501:8080"
    depends_on:
      - backend
    networks:
      - resume-net


networks:
  resume-net:
    driver: bridge

volumes:
  db_data:
